<?php
// Get the task from the session
require_once(HOME . "/classes/RCMETWizardTask.class.php");
$task = unserialize($_SESSION['wizardTask']);
$task->setStep('selectPlotOptions');

if (isset($_POST['save'])) {
	// Nothing to save, yet
	
	$task->nextStep();
}
$task->showPreviousNextLinks();
?>
<div class="section">
<div class="row">
<div class="span12">
<h2 class="title">Plot Options</h2>
<div class="box">
<div class="box-content">
<fieldset id="variableAssignmentSelector" class="">
	<legend>Custom Plotting Options</legend>
<form method="POST">
	Depending upon your current settings, it may be possible to
	customize some aspects of the generated plots:<hr/>
	
<h3>Customize Plots</h3>
	<input type="checkbox" name="seasonalCycle" disabled="disabled" style="vertical-align:middle;"/> 
		Do you wish to customize the plots generated by this toolkit?
	
	<br/><br/>
	<div>
	<p>If the information above is correct, please click: 
	<input type="submit" name="save" value="Continue" class="btn btn-primary"/>
	</p>
	</div>	
</form>
</fieldset>
</div>
</div>
</div>
</div>
</div>
