#!/bin/bash

EXTRACTOR_BIN='/usr/local/wrm/deploy/metextraction/AIRSNetCDFExtractor.php';
NCDUMP_BIN='/usr/local/netcdf-4.1.1/bin/ncdump';
DATA_DIR=/usr/local/wrm/data/AIRX3STD/2002-08-30_upto_2004-01-01/2002
MET_OUT_DIR=/usr/local/wrm/met-out

GRANULE=$1


# Un gzip the input data
#gunzip -v $DATA_DIR/$GRANULE.nc.gz;

# Extract the data into segments
$EXTRACTOR_BIN $NCDUMP_BIN $DATA_DIR/$GRANULE.nc $MET_OUT_DIR \
Temperature_A,Temperature_D,TotH2OVap_A,TotH2OVap_D,H2OVapMMR_A,H2OVapMMR_D,TotCldLiqH2O_A,TotCldLiqH2O_D,CloudFrc_A,CloudFrc_D,SurfAirTemp_A,SurfAirTemp_D,SurfSkinTemp_A,SurfSkinTemp_D,GPHeight_A,GPHeight_D,FineCloudFrc_A,FineCloudFrc_D,RelHumid_A,RelHumid_D 1500000;

