'reinit'
'open /Users/kimwhitehall/Documents/HU/research/mccsearch/caseStudy1/TRMMnetcdfCEs/ctlFiles/20090831000000F1CE1.ctl'
'set grads off'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'set gxout shaded on'
'set datawarn off'
'set gxout shaded on'
'set csmooth on'

'd precipAcc'
'run cbarn'
'printim /Users/kimwhitehall/Documents/HU/research/mccsearch/caseStudy1/images/20090831000000F1CE1.gif x800 y600 white'
'quit'
